# Generated by Django 3.1 on 2020-08-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200815_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod',
            new_name='Product',
        ),
    ]
